on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DavidAnson/markdownlint-cli2-action@v4
        with:
          globs: |
            *.md
            #MAINTAINERS.md

  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Check links
        run: npx markdown-link-check -c .markdown-link-check-config.json README.md
